# Basic
title: 小菜菜程序媛
subtitle: A blog-orientation theme for Frieda
welcome_message: <a href="https://github.com/crazygirlfym" target="_blank">github address</a>
description: Love coding, coding love me!.
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://crazygirlfym/crazygirlfym.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/crazygirlfym'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: crazygirlfym
    # duoshuo: 
    
# Social
social:
    weibo: crazygirlfym 
    github: crazygirlfym
    twitter: crazygirlfym
    gplus: 107108267983477358170
    mail: crazygirlfym@gmail.com

# Google Analytics
ga:
    id: UA-130125823-1
    #host: 
